name: 'run'

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'setup python'
        uses: actions/setup-python@master
        with: 
          python-version: 3.7

      - name: requirements
        run : pip3 install -r requirements.txt

      - name: main
        env:
          cookie_enshan: ${{ secrets.cookie_enshan }}
        run: |
          python3 ../Enshan/Enshan.py
          
